// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/psx-redesign/Editorial.tsx": () => import("../components/mockups/psx-redesign/Editorial.tsx"),
  "./components/mockups/psx-redesign/Terminal.tsx": () => import("../components/mockups/psx-redesign/Terminal.tsx")
};
